import type { FaqEntry } from "@/components/faq-section"

export const FAQ_HOME: FaqEntry[] = [
  { q: "Le brief est-il personnalisé pour mon entreprise ?", a: "Non, et c'est un choix. RADAR couvre un marché entier : le brief est le même pour toutes les entreprises qui y opèrent. C'est ce qui permet d'y consacrer un travail de fond impossible à produire maison par maison. Quand une action dépend de votre configuration, elle est explicitement segmentée — par exemple selon que vous vendez en direct ou par un distributeur.", icon: "cpu" },
  { q: "Comment RADAR sait ce qui compte sur mon marché ?", a: "Chaque marché suivi a sa fiche : périmètre et frontières, chaîne de valeur, dépendances communes à toute la filière, acteurs structurants nommés, cadre réglementaire applicable, cycles et vocabulaire du métier. Les sept radars sont balayés contre cette fiche chaque semaine, et tout ce qui ne la touche pas est jeté.", icon: "eye" },
  { q: "En quoi RADAR est différent d'une newsletter sectorielle ?", a: "Une newsletter raconte ce qui s'est passé. RADAR va jusqu'au bout : ce que le fait change en proportion de vos coûts, sous quel délai, et quelle est la première chose à faire — testable en sept jours. Et chaque sujet reste suivi d'une semaine à l'autre jusqu'à ce qu'il soit traité, ce qu'aucune newsletter ne fait.", icon: "shield" },
  { q: "RADAR REGULATION remplace-t-il un conseil juridique ?", a: "Non. RADAR informe et alerte sur les évolutions réglementaires qui vous concernent ; toute décision juridique doit être validée par un professionnel compétent.", icon: "shield" },
  { q: "Combien de temps ça me prend chaque semaine ?", a: "Cinq minutes. Le brief hebdomadaire tient sur cinq points : le changement majeur, l'opportunité, le risque, ce que font vos concurrents, ce que vous devriez faire.", icon: "clock" },
  { q: "Puis-je annuler à tout moment ?", a: "Oui, sans engagement de durée sur les formules RADAR et RADAR PRO. ADVISORY et ENTERPRISE sont contractualisés à la mise en place.", icon: "xcircle" },
]
