import type { FaqEntry } from "@/components/faq-section"

export const FAQ_HOME: FaqEntry[] = [
  { q: "Le brief est-il personnalisé pour mon entreprise ?", a: "Non, et c'est un choix. RADAR couvre un marché entier : le brief est le même pour toutes les entreprises qui y opèrent. C'est ce qui permet d'y consacrer un travail de fond impossible à produire maison par maison. Quand une action dépend de votre configuration, elle est explicitement segmentée — par exemple selon que vous vendez en direct ou par un distributeur.", icon: "cpu" },
  { q: "Comment RADAR sait ce qui compte sur mon marché ?", a: "Chaque marché suivi a sa fiche : périmètre et frontières, chaîne de valeur, dépendances communes à toute la filière, acteurs structurants nommés, cadre réglementaire applicable, cycles et vocabulaire du métier. Les sept radars sont balayés contre cette fiche chaque semaine, et tout ce qui ne la touche pas est jeté.", icon: "eye" },
  { q: "En quoi RADAR est différent d'une newsletter sectorielle ?", a: "Trois choses. La couverture : il faut cinq newsletters pour couvrir un marché, RADAR le couvre en entier, et une rubrique sans actualité l'écrit plutôt que de disparaître. La situation : chaque information dit ce qu'elle change pour une entreprise du marché, pas seulement qu'elle s'est produite. Et le suivi : un sujet reste ouvert d'une semaine à l'autre jusqu'à sa résolution.", icon: "shield" },
  { q: "RADAR REGULATION remplace-t-il un conseil juridique ?", a: "Non. RADAR informe et alerte sur les évolutions réglementaires qui vous concernent ; toute décision juridique doit être validée par un professionnel compétent.", icon: "shield" },
  { q: "Combien de temps ça me prend chaque semaine ?", a: "Dix minutes. Vous parcourez les titres des rubriques et vous vous arrêtez sur ce qui vous concerne — comme dans un journal. La une, l'agenda des échéances et l'action de la semaine se lisent en trois minutes si vous n'avez que ça.", icon: "clock" },
  { q: "Puis-je annuler à tout moment ?", a: "Oui, sans engagement de durée sur les formules RADAR et RADAR PRO. ADVISORY et ENTERPRISE sont contractualisés à la mise en place.", icon: "xcircle" },
]
